accountLinking:
  appClientId: <CLIENT_ID>
  authGrantType: AUTH_CODE
  authorizationUrl: https://<SERVER_NAME>:<SERVER_PORT>/oauth/oauth_login.cgi
  linkingType: OAUTH
  scopes:
  - AudioStation.voiceassistant
  tokenUrl: https://<SERVER_NAME>:<SERVER_PORT>/oauth/oauth_token.cgi
  useBasicAuthHeader: true
defaultLocale: en
localizedSettings:
  displayName: Audio Station
  pronunciation: Audio Station
  voice: female_3
projectId: <PROJECT_ID>
surfaceRequirements:
  minimumRequirements:
  - capability: AUDIO_OUTPUT
  - capability: MEDIA_RESPONSE_AUDIO
testingInstructions: na
